name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d-%H-%M")
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/cargolink:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/cargolink:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cargolink:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cargolink:$TIMESTAMP